# Generated by Django 4.1.7 on 2023-03-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('roll_number', models.IntegerField()),
                ('telugu', models.IntegerField()),
                ('english', models.IntegerField()),
                ('botany', models.IntegerField()),
                ('zoology', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('author', models.CharField(max_length=55)),
            ],
        ),
    ]
